# Generated by Django 4.1.4 on 2022-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Proceeded', 'Proceeded')], max_length=25, verbose_name='Статус'),
        ),
    ]
